"""Generate improvement proposals from analysis."""

import json
import logging
from datetime import datetime
from typing import Any

from autodev.config import AutoDevConfig

logger = logging.getLogger(__name__)


class ProposalGenerator:
    """Generate actionable improvement proposals."""

    def __init__(self, config: AutoDevConfig):
        self.config = config

    def generate(self, analysis: dict[str, Any]) -> list[dict[str, Any]]:
        """Generate proposals from analysis results."""
        proposals = []

        for repo_name, repo_analysis in analysis.get("repositories", {}).items():
            if "error" in repo_analysis:
                logger.warning(f"Skipping {repo_name} due to analysis error")
                continue

            opportunities = repo_analysis.get("opportunities", [])

            # Sort by priority
            opportunities.sort(key=lambda x: x.get("priority", 5))

            # Apply daily limits per category
            category_counts: dict[str, int] = {}
            for category_config in self.config.categories:
                category_counts[category_config.name] = 0

            for opp in opportunities:
                category = opp.get("category", "other")
                max_per_day = 3  # Default

                for cat_config in self.config.categories:
                    if cat_config.name == category:
                        max_per_day = cat_config.max_per_day
                        if not cat_config.enabled:
                            continue

                if category_counts.get(category, 0) >= max_per_day:
                    continue

                category_counts[category] = category_counts.get(category, 0) + 1

                proposal = self._create_proposal(repo_name, opp)
                proposals.append(proposal)

                if len(proposals) >= self.config.max_issues_per_day:
                    break

            if len(proposals) >= self.config.max_issues_per_day:
                break

        return proposals

    def _create_proposal(
        self,
        repo_name: str,
        opportunity: dict[str, Any],
    ) -> dict[str, Any]:
        """Create a proposal from an opportunity."""
        # Find repo owner
        owner = "privacybydesign"
        for repo_config in self.config.repositories:
            if repo_config.name == repo_name:
                owner = repo_config.owner
                break

        return {
            "repo": f"{owner}/{repo_name}",
            "repo_name": repo_name,
            "title": f"[AutoDev] {opportunity['title']}",
            "category": opportunity.get("category", "improvement"),
            "priority": opportunity.get("priority", 3),
            "effort": opportunity.get("effort", "small"),
            "body": self._format_issue_body(opportunity),
            "labels": [
                "autodev-proposal",
                f"category:{opportunity.get('category', 'improvement')}",
                f"effort:{opportunity.get('effort', 'small')}",
            ],
            "files_affected": opportunity.get("files_affected", []),
            "created_at": datetime.utcnow().isoformat(),
        }

    def _format_issue_body(self, opportunity: dict[str, Any]) -> str:
        """Format the issue body in markdown."""
        return f"""## Description

{opportunity.get('description', 'No description provided.')}

## Rationale

{opportunity.get('rationale', 'No rationale provided.')}

## Files Affected

{self._format_files_list(opportunity.get('files_affected', []))}

## Acceptance Criteria

- [ ] Implementation follows existing code patterns
- [ ] Tests added/updated for changes
- [ ] Documentation updated if needed
- [ ] CI passes

## Implementation Notes

This issue was automatically generated by [AutoDev Agent](https://github.com/privacybydesign/autodev-agent).

**Priority:** {opportunity.get('priority', 'N/A')}
**Effort:** {opportunity.get('effort', 'N/A')}
**Category:** {opportunity.get('category', 'N/A')}

---
*To approve this issue for implementation, add the `autodev-approved` label.*
*AutoDev will create a draft PR in the next nightly run.*
"""

    def _format_files_list(self, files: list[str]) -> str:
        """Format a list of files as markdown."""
        if not files:
            return "_Files to be determined during implementation_"
        return "\n".join(f"- `{f}`" for f in files)


def main():
    """CLI entry point."""
    import argparse
    from pathlib import Path

    parser = argparse.ArgumentParser()
    parser.add_argument("--analysis", type=Path, required=True)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    from autodev.config import load_config

    config = load_config(args.config)
    with open(args.analysis) as f:
        analysis = json.load(f)

    generator = ProposalGenerator(config)
    proposals = generator.generate(analysis)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w") as f:
        json.dump(proposals, f, indent=2)

    if args.dry_run:
        print(f"Generated {len(proposals)} proposals (dry run)")
        for p in proposals:
            print(f"  - [{p['repo']}] {p['title']}")


if __name__ == "__main__":
    main()
